SKILL_LIBRARY = [
    "excel",
    "advanced excel",
    "sap",
    "oracle",
    "erp",
    "power bi",
    "sql",
    "python",
    "ifrs",
    "vas",
    "acca",
    "cpa",
    "audit",
    "tax",
    "bookkeeping",
    "financial reporting",
    "budgeting",
    "forecasting",
    "english",
    "communication",
    "teamwork",
]